### ISSUE TITLE
WIT as interface definiton.

### ISSUE THREAD

**Issue by zie1ony** [odradev/casper-contract-schema#6]
Bytecode Alliance is working on the extension to WASM's module called components. It's the next big change to the WASM ecosystem. It allows composing multiple WASM binaries into one. Wasmtime already implements it.

For components to work with each other they need an interface. Their standard is called WIT: https://component-model.bytecodealliance.org/design/wit.html.

There is also Rust lib for it: https://docs.rs/witgen/latest/witgen/ and JS: https://github.com/bytecodealliance/ComponentizeJS.

What do you think? Maybe for 2.0?

**Comment by melpadden** [comment]
I think this looks like something we need to make a plan for and implement, surely. In terms of scheduling,  time-to-market is key for us so I would descope it for the current release.

**Comment by zie1ony** [comment]
Reopen when needed.
